Crm 12 entity customers
Clanhouse/mecha-crm-app pull request #19
Opened 2021-04-26 17:42 UTC by MateuszPioro

Create pull request.

2021-04-26 18:20 UTC, Fellway requested changes

2021-04-26 18:20 UTC, Fellway commented on backend/src/main/java/com/crm/App.java
> +
It's not needed

2021-04-26 18:20 UTC, Fellway commented on backend/src/main/java/com/crm/App.java
> +
It's not needed

2021-04-26 18:20 UTC, Fellway commented on backend/src/main/java/com/crm/model/db/CarEntity.java
> +    Set<CustomerEntity> cars = new HashSet<>();
private

2021-04-26 18:20 UTC, Fellway commented on backend/src/main/java/com/crm/model/db/CustomerEntity.java
> +@Builder
Builder is not needed

2021-04-26 18:20 UTC, Fellway commented on backend/src/main/java/com/crm/model/db/CustomerEntity.java
> +@AllArgsConstructor
It's not needed

2021-04-26 18:20 UTC, Fellway commented on backend/src/main/java/com/crm/model/db/CustomerEntity.java
> +    Set<CarEntity> cars = new HashSet<>();
private

2021-04-26 18:20 UTC, Fellway commented on db-migration/pom.xml
> +                    <password>smentek12</password>
remove this from PR

2021-04-29 18:05 UTC, SteelWro commented on backend/src/main/java/com/crm/model/db/CustomerEntity.java
> +
Cause we use Collection like Set and other we need to ovveride `equals `and `hashcode `methods

2021-05-05 19:03 UTC, Fellway approved these changes

2021-05-05 19:03 UTC, merged