Crm 31 jwt
Clanhouse/mecha-crm-app pull request #29
Opened 2021-05-09 09:14 UTC by daniel250592

2021-05-11 19:54 UTC, Fellway requested changes

2021-05-11 19:54 UTC, Fellway commented on backend/src/main/java/com/crm/api/v1/AuthenticationController.java
> +        } catch (DisabledException e) {
final

2021-05-11 19:54 UTC, Fellway commented on backend/src/main/java/com/crm/api/v1/AuthenticationController.java
> +        } catch (BadCredentialsException e) {
final

2021-05-11 19:54 UTC, Fellway commented on backend/src/main/java/com/crm/api/v1/AuthenticationController.java
> +    private void authenticate(String username, String password) throws Exception {
finals

2021-05-11 19:54 UTC, Fellway commented on backend/src/main/java/com/crm/config/SecurityConfiguration.java
> +    protected void configure(AuthenticationManagerBuilder auth) throws Exception {
final

2021-05-11 19:54 UTC, Fellway commented on backend/src/main/java/com/crm/config/UserPrincipal.java
> +        return null;
Mark it as TODO

2021-05-11 19:54 UTC, Fellway commented on backend/src/main/java/com/crm/config/UserPrincipal.java
> +    @Override
Mark as TODO

2021-05-11 19:54 UTC, Fellway commented on backend/src/main/java/com/crm/config/UserPrincipal.java
> +    @Override
Mark as TODO

2021-05-11 19:54 UTC, Fellway commented on backend/src/main/java/com/crm/config/UserPrincipal.java
> +    public boolean isCredentialsNonExpired() {
Mark as TODO

2021-05-12 11:29 UTC, SteelWro commented on backend/src/main/java/com/crm/config/SecurityConfiguration.java
>  @Configuration
`@RequiredArgsConstructor` annotation instead of parameterized constructor

2021-05-12 11:42 UTC, SteelWro commented on backend/src/main/java/com/crm/service/JwtUserDetailsService.java
> +@Service
`@RequiredArgsConstructor`

2021-05-12 11:47 UTC, SteelWro commented on backend/src/main/java/com/crm/exception/UnauthorizedException.java
> +public class UnauthorizedException extends RuntimeException {
What purpose does empty exception class serve?

2021-05-12 11:49 UTC, SteelWro commented on backend/src/main/java/com/crm/dto/response/JwtResponse.java
> +@Getter
`@RequiredArgsConstructor` annotation instead your constructor

2021-05-12 13:50 UTC, daniel250592 commented on backend/src/main/java/com/crm/api/v1/AuthenticationController.java
> +        } catch (DisabledException e) {
resolved

2021-05-12 13:51 UTC, daniel250592 commented on backend/src/main/java/com/crm/api/v1/AuthenticationController.java
> +        } catch (BadCredentialsException e) {
resolved

2021-05-12 13:53 UTC, daniel250592 commented on backend/src/main/java/com/crm/config/SecurityConfiguration.java
> +    protected void configure(AuthenticationManagerBuilder auth) throws Exception {
resolved

2021-05-12 13:53 UTC, daniel250592 commented on backend/src/main/java/com/crm/config/UserPrincipal.java
> +        return null;
resolved

2021-05-12 13:54 UTC, daniel250592 commented on backend/src/main/java/com/crm/config/SecurityConfiguration.java
> +//    protected void configure(final HttpSecurity http) throws Exception {
resolved

2021-05-12 14:50 UTC, daniel250592 commented on backend/src/main/java/com/crm/config/filter/JwtRequestFilter.java
> +    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException {
resolved

2021-05-12 14:51 UTC, daniel250592 commented on backend/src/main/java/com/crm/config/filter/JwtRequestFilter.java
> +    public JwtRequestFilter(final JwtUserDetailsService userDetailsService, JwtTokenUtils jwtTokenUtils) {
resolved

2021-05-12 14:51 UTC, daniel250592 commented on backend/src/main/java/com/crm/config/JwtTokenUtils.java
> +        return claimsResolver.apply(claims);
resolved

2021-05-12 14:52 UTC, daniel250592 commented on backend/src/main/java/com/crm/config/JwtTokenUtils.java
> +        return expiration.before(new Date());
resolved

2021-05-12 14:53 UTC, daniel250592 commented on backend/src/main/java/com/crm/service/JwtUserDetailsService.java
> +@Service
resolved

2021-05-12 14:56 UTC, daniel250592 commented on backend/src/main/java/com/crm/exception/UnauthorizedException.java
> +public class UnauthorizedException extends RuntimeException {
I added new constructor with String message.

2021-05-12 14:57 UTC, daniel250592 commented on backend/src/main/java/com/crm/dto/response/JwtResponse.java
> +@Getter
resolved

2021-05-14 13:47 UTC, daniel250592 commented on backend/src/main/java/com/crm/config/filter/FilterExceptionHandler.java
> +public class FilterExceptionHandler extends OncePerRequestFilter {
done

2021-05-14 13:52 UTC, daniel250592 commented on backend/src/main/java/com/crm/model/db/AccountEntity.java
> +@AllArgsConstructor
a whole entity?

2021-05-14 13:52 UTC, daniel250592 commented on backend/src/main/java/com/crm/model/db/RoleEntity.java
> +@AllArgsConstructor
I think I need this for tests purposes.

2021-05-17 16:23 UTC, Fellway requested changes

2021-05-17 16:23 UTC, Fellway commented on backend/pom.xml
> +        <dependency>
Why its added here?

2021-05-17 16:23 UTC, Fellway commented on backend/src/main/java/com/crm/config/SecurityConfiguration.java
> +        CorsConfiguration configuration = new CorsConfiguration();
can be final

2021-05-17 16:23 UTC, Fellway commented on backend/src/main/java/com/crm/model/db/AccountEntity.java
> +@AllArgsConstructor
Just AllArgsConstructor

2021-05-17 16:47 UTC, Fellway requested changes

2021-05-17 16:47 UTC, Fellway commented on backend/src/test/java/com/crm/config/JwtRequestFilterTest.java
> +class JwtRequestFilterTest {
It's terrible :D Call me and I will explain you how it should looks like

2021-05-17 16:47 UTC, Fellway commented on backend/src/test/java/com/crm/service/JwtUserDetailsServiceTest.java
> +class JwtUserDetailsServiceTest {
Same as above

2021-05-22 13:25 UTC, Fellway requested changes

2021-05-23 20:53 UTC, Fellway approved these changes

2021-05-23 20:53 UTC, merged