CRM 33 - ExceptionHandler
Clanhouse/mecha-crm-app pull request #30
Opened 2021-05-15 16:40 UTC by ell96p

2021-05-15 16:44 UTC, daniel250592 commented on backend/src/main/java/com/crm/exception/AppExceptionHandler.java
> +    public ResponseEntity<ErrorResponse> handleException (Exception exc, HttpServletRequest request){
final Exception exc,final HttpServletRequest request

2021-05-15 16:44 UTC, daniel250592 commented on backend/src/main/java/com/crm/exception/AppExceptionHandler.java
> +    private String getSource(HttpServletRequest request) {
final

2021-05-16 14:23 UTC, ell96p commented on backend/src/main/java/com/crm/exception/AppExceptionHandler.java
> +    public ResponseEntity<ErrorResponse> handleException (Exception exc, HttpServletRequest request){
okk

2021-05-16 14:23 UTC, ell96p commented on backend/src/main/java/com/crm/exception/AppExceptionHandler.java
> +    private String getSource(HttpServletRequest request) {
ok

2021-05-17 16:01 UTC, Fellway requested changes

2021-05-18 18:50 UTC, ell96p commented on backend/src/main/java/com/crm/exception/AppExceptionHandler.java
> +
ok

2021-05-18 18:50 UTC, ell96p commented on backend/src/main/java/com/crm/exception/AppExceptionHandler.java
> +    public static final String SOURCE_ERROR_MESSAGE = "Unknown source";
ok

2021-05-18 18:50 UTC, ell96p commented on backend/src/main/java/com/crm/exception/AppExceptionHandler.java
> +            source = request.getAttribute(HandlerMapping.PATH_WITHIN_HANDLER_MAPPING_ATTRIBUTE).toString();
ok

2021-05-18 18:50 UTC, ell96p commented on backend/src/main/java/com/crm/exception/AppExceptionHandler.java
> +            source = SOURCE_ERROR_MESSAGE;
ok

2021-05-18 18:50 UTC, ell96p commented on backend/src/main/java/com/crm/exception/ErrorResponse.java
> +@NoArgsConstructor
ok

2021-05-18 22:05 UTC, Fellway approved these changes

2021-05-18 22:06 UTC, merged